# Generated by Django 5.0.2 on 2024-02-19 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_item', models.CharField(max_length=50)),
                ('labor_costs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('material_costs', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=255)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('man_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('special_service', models.BooleanField(default=False)),
                ('date_serviced', models.DateTimeField()),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('maintenance_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asset.maintenanceitem')),
                ('cost_analysis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.costanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.CharField(max_length=50)),
                ('labor_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area_serviced', models.CharField(max_length=50)),
                ('wo_complete', models.BooleanField(default=True)),
                ('asset_used', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asset.asset')),
                ('maintenance_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asset.maintenanceitem')),
            ],
        ),
        migrations.AddField(
            model_name='costanalysis',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.task'),
        ),
    ]
