# Generated by Django 5.0.2 on 2024-02-19 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='cost_analysis',
        ),
        migrations.AddField(
            model_name='costanalysis',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.contract'),
        ),
    ]
