# Generated by Django 5.0.2 on 2024-02-19 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('work_crew', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.workcrew')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateTimeField()),
                ('work_crew', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.workcrew')),
            ],
        ),
    ]
