# Generated by Django 5.0.2 on 2024-02-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkSheets',
            new_name='WorkSheet',
        ),
    ]
